VolvoCore/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('opty.urls', namespace='opty')),
    url(r'^api/', include('account.urls', namespace='account')),
    url(r'^api/', include('commons.user_auth.urls', namespace='user_auth')),
    url(r'^api/', include('competitor.urls', namespace='competitor')),
    url(r'^api/', include('dealer.urls', namespace='dealer')),
    ]

VolvoSkin/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^api/', include('commons.user_auth.urls', namespace='user_auth')),
    url(r'fcm/', include('fcm.urls')),
    url(r'^api/', include('cv360.mobile.opty.urls', namespace='opty')),
    url(r'^api/', include('cv360.mobile.account.urls', namespace='account')),
]

Volvo_Core/Opty/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from Opty import views

urlpatterns = [
    url(r'', views.OptyDetails.as_view(),
        name='Opty_details')
    ]

Volvo_Core/Volvo_Core/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from Opty import urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/opty', include('Opty.urls', namespace='Opty_details'))
]

Volvo_Skin/Opty/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from Opty import views

urlpatterns = [
    url(r'', views.OptySearchDetails.as_view(),
        name='Opty_details')
    ]

Volvo_Skin/Volvo_Skin/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls import url,include

from Opty import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/opty', include('Opty.urls', namespace='Opty_details'))
    ]

account/urls.py
from account.views import views_solr
from django.conf.urls import url

urlpatterns = [

    url(r'^acc/by_pos/$',
        views_solr.GetAccByPosAPIView.as_view(),
        name='get_acc_by_pos'),


]

commons/position/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from commons.position import views

urlpatterns = [
    url(r'^get/position/$', views.PositionDetails.as_view(),
        name='refresh-token'),
]

commons/user_auth/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from commons.user_auth.views import AddSolrUserView

urlpatterns = [
    url(r'^add/user/$',
        AddSolrUserView.as_view(),
        name='add_solr_user'),

]

urlpatterns = format_suffix_patterns(urlpatterns)

competitor/urls.py
from competitor.views import views_solr
from django.conf.urls import url

urlpatterns =[

    url(r'^competitor/byoptyId/$',views_solr.GetCompetitorByOptyIDAPIView.as_view(),
        name='get_competitor_byoptyID'),
    ]

cv360/mobile/account/urls.py
from django.conf.urls import url


from cv360.mobile.account import views


urlpatterns=[

    url(r'^get/account/bypositionID/$', views.GetAccountByPositionID.as_view(),
        name='get_acc_by_position'),
    ]

cv360/mobile/opty/urls.py
from django.conf.urls import url
from cv360.mobile.opty import views

urlpatterns = [

    url(r'^get/opty/bypos/$', views.GetOptyByPosition.as_view(),
        name='get_opty_by_position'),
    url(r'^createopty/$', views.Createopty.as_view(),
        name='create_opty'),
]

dealer/urls.py
from django.conf.urls import url

from dealer.views import view_siebel

urlpatterns = [

    url(r'^sync/dealer/$',
        view_siebel.DealerSyncView.as_view(),
        name='dealer_sync'),
]

holiday_tracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls')),
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^login/', include('login.urls')),
    url(r'^leaves/', include('leaves.urls')),
]

home/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib.auth.decorators import login_required
from rest_framework.urlpatterns import format_suffix_patterns
app_name = 'home'

urlpatterns = [
    url(r'^$', login_required(views.Homeview.as_view(template_name="home/home.html")),name='home'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

leaves/urls.py
from django.conf.urls import url
from . import views

app_name = 'leaves'

urlpatterns = [
    url(r'^$', views.index, name='index')
]

login/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib.auth.views import login,logout
from rest_framework.urlpatterns import format_suffix_patterns


app_name = 'login'

urlpatterns = [
    url(r'^$', login, {'template_name':'login/login.html'},name='log'),
    url(r'^login/$', logout, name='logout',kwargs={'next_page': '/login/'})
]

urlpatterns = format_suffix_patterns(urlpatterns)

opty/urls.py
from opty.views import views_solr
from django.conf.urls import url


urlpatterns = [
    url(r'^opty/by_pos/$',views_solr.GetOptyByPosAPIView.as_view(),
        name='get_opty_by_pos'),
    url(r'^createopty/$',views_solr.CreateOptyAPIView.as_view(),
        name='create_opty'),


]

position/urls.py
from position.views import views
from django.conf.urls import url

urlpatterns = [

url(r'^get/position/$', GetPosition.as_view(),
        name='get_position'),
]

home/models.py
from __future__ import unicode_literals
from django.db import models
from login.models import UserProfile
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

opty/models.py
from __future__ import unicode_literals
from django.db import models

class Opty(models.Model):
    """
    Base class for storing Siebel Opty ID and Opty ID.
    """
    opty_id = models.CharField(max_length=200, blank=False)
    seibel_opty_id = models.CharField(max_length=200, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        db_table = 'Opty'

dealer/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from django.shortcuts import render
from rest_framework.generics import RetrieveUpdateDestroyAPIView
from models import UserProfile
from rest_framework.views import APIView
from rest_framework.renderers import TemplateHTMLRenderer
from login.serializers import UserProfileSerializer
from rest_framework.response import Response
from django.utils.decorators import method_decorator

class Homeview(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'home/home.html'

    @method_decorator(login_required)
    def get(self, request):
        args = UserProfile.objects.all()
        serializer = UserProfileSerializer(args, many=True)
        return Response({'user': request.user})

'''
def profile(request):
    args = {'user': request.user}
    return render(request,'home/home.html',args)'''

leaves/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def index(request):
    return HttpResponse("<h2>This is leaves section</h2>")

login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render
from rest_framework.generics import RetrieveUpdateDestroyAPIView
from .serializers import UserProfileSerializer
from .models import UserProfile

opty/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

home/templates/home/home.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Audetemi Home page</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
     <link rel="stylesheet" href="{% static 'home/home.css' %}">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
   <nav>
        <section class="nav-container"></section>
          <aside class="Logo"></aside>
           <div class="menu">
             <a href="{% url 'login:logout' %}"><img src="https://maxcdn.icons8.com/Share/icon/User_Interface//logout_rounded_up1600.png" width="60" height="60"></a>
           </div>
          <div class="audetemi">
             <img src="https://audetemi.com/assets/img/audetemi-logo-500px.png" width="600" height="60">
          </div>
    <div class="b">
          <li></li>
          <li></li>
           <div class="user">
           <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiq3x7tjZiOp7p6gL8wLVbgkRpkkizVpmcefJlLTSZaVfHJ5QoUQ" width="250" height="250">
           <div class="demo">
               <a href="link3.html"><img src="https://www.iconexperience.com/_img/i_collection_png/256x256/plain/pencil.png" width="30" height="30"></a>
           </div>
         </div>
         <div class="info">
           <ul>
           <li>Username:-{{ user }}                                         </li>
           <li>Email ID:-{{ user.email }}                                     </li>
           <li>Emp Designation :-{{ user.userprofile.emp_desig }}                                  </li>
           <li>Emp ID :- {{ user.userprofile.emp_id }}                                            </li>
           <li>MOb No:- {{ user.userprofile.mobile_number }}                                           </li>
           <li>Total Leaves:- {{ user.userprofile.leaves }}                                      </li>
           <li>Leaves Taken                                      </li>
           <li>Leave remaining                                   </li>
         </ul>
        </div>
    </div>
    <div class="foter">
    </div>
  </nav>
    <p class="leave">
        <a href="{% url 'leaves:index' %}"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_PpgFhEDEUI_i_vFfVismpkDh7EhSwFljsUsAwhRgvFR9nysMqw" height="200" width="200"></a>
     <p1 class="home">
        <a href="link2.html"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX65MhtbOegQxC8XVqnWZ3Qc7mOzBVPem3kJDYkt9YVPbAnS-sBQ" height="190" width="190"></a>
    </p1>
  </p>
  <k class="leave_header">
       <p>Leave form <p>
  </k>
     <k1 class="home_header">
       <p1>Work from home<p1>
     </k1>

  <p class="calender">
      <a href="link2.html"><img src="http://downloadicons.net/sites/default/files/calendar-icon-65989.png" height="200" width="200"></a>
   <p1 class="export">
      <a href="link2.html"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUfOB6LDJr9OkmdJk5GX7j7lpgrIUnLhqz_6OrW_I-_jWCDAeA" height="200" width="200"></a>
  </p1>
</p>
   <l class="calender_header">
     <p>Calender <p>
   </l>
     <l1 class="pdf_header">
       <p1>Export pdf<p1>
   </l1>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>